In [0]:
import pandas as pd

In [0]:
#addition of two numbers

a=9
b=9
c=a+b
print(c)

18


In [0]:
#find maximum from a list of numbers

lis=[9,5,6]
max=0
for i in lis:
  if i>max:
    max=i
print(max)

9


In [0]:
#find reverse of list of numbers

a=[3,5,7,9]
b=[]
for i in range(len(a)-1,-1,-1):
  b.append(a[i])
print(b)

[9, 7, 5, 3]


In [0]:
#fibinacci series

a=0
b=1
print(a)
print(b)
n=7
for i in range(1,n):
  c=a+b
  a=b
  b=c
  print(c)

0
1
1
2
3
5
8
13


In [0]:
#fibinacci series by function

def fibonacci(n):
  a=0
  b=1
  print(a)
  print(b)
  for i in range(1,n):
    c=a+b
    a=b
    b=c
    print(c)

In [0]:
fibonacci(5)

0
1
1
2
3
5


In [0]:
#numpy
import numpy as np
str=np.array([[1,2,3],[4,5,6]])
print(str.ndim)
print(str.shape)
print(str.size)
print(str.dtype)


2
(2, 3)
6
int64


In [0]:
a=np.array([[7,8,9],[8,5,6]])
b=np.array([[1,2,3],[4,7,8],[4,5,2]])

In [0]:
p=np.dot(a,b)

In [45]:
p

array([[ 75, 115, 103],
       [ 52,  81,  76]])

In [0]:
#generating random vectors:

a=np.random.uniform(low=1,high=5,size=(3,3))
#a=np.random.randint(1,7,size=(3,3))

b=np.random.uniform(low=1,high=6,size=(3,3))

In [57]:
#vector a
a

array([[2, 1, 2],
       [3, 2, 6],
       [4, 4, 4]])

In [51]:
#vector b

b

array([[1.33677371, 5.87173916, 2.94038473],
       [2.55070178, 3.50125666, 4.41834027],
       [3.1349605 , 5.0046602 , 2.70234556]])

In [52]:
#addition
a+b

array([[ 4.02835725, 10.6118496 ,  6.87257438],
       [ 5.44769226,  6.42867877,  8.26464971],
       [ 7.31616738,  6.3492351 ,  4.30618208]])

In [53]:
#dot product

np.dot(a,b)

array([[28.01590546, 52.07989278, 39.48384725],
       [23.39762963, 46.50950035, 31.8466708 ],
       [14.04690115, 37.28531481, 22.56926681]])

In [54]:
#cross product

np.cross(a,b)

array([[-9.15104354, -2.65784343,  9.46782148],
       [-0.53256955, -2.98910138,  2.67612644],
       [-4.39315078, -6.27110173, 16.71033048]])

In [55]:
#addition

np.add(a,b)

array([[ 4.02835725, 10.6118496 ,  6.87257438],
       [ 5.44769226,  6.42867877,  8.26464971],
       [ 7.31616738,  6.3492351 ,  4.30618208]])

In [0]:
from sklearn import datasets


In [0]:
iris = datasets.load_iris()

In [0]:
a=np.random.uniform(low=1,high=5,size=(3,3))

In [0]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'A':[4,5,6,7],'B':[10,20,30,40], 'C':[100,50,-30,-50]})
new_data = np.random.rand(4,3)
df2 = pd.DataFrame(new_data, columns=['I','II','III'], index=df1.index)
df_new = df1 + df2

In [0]:
dfnew =pd.concat((df1, df2), axis=1)

In [35]:
df3=df1.append(df2,ignore_index=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


In [36]:
df3.dropna()

Empty DataFrame
Columns: [A, B, C, I, II, III]
Index: []

In [0]:
df3new=df3.fillna(0)

In [38]:
df3new

A     B      C         I        II       III
0  4.0  10.0  100.0  0.000000  0.000000  0.000000
1  5.0  20.0   50.0  0.000000  0.000000  0.000000
2  6.0  30.0  -30.0  0.000000  0.000000  0.000000
3  7.0  40.0  -50.0  0.000000  0.000000  0.000000
4  0.0   0.0    0.0  0.646053  0.856210  0.142555
5  0.0   0.0    0.0  0.368435  0.577341  0.799733
6  0.0   0.0    0.0  0.441040  0.998293  0.204467
7  0.0   0.0    0.0  0.759758  0.749011  0.731621

In [39]:
df3new.iloc[2:,3:]

I        II       III
2  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000
4  0.646053  0.856210  0.142555
5  0.368435  0.577341  0.799733
6  0.441040  0.998293  0.204467
7  0.759758  0.749011  0.731621

In [40]:
df3new.loc[:,["I","II","III"]]

I        II       III
0  0.000000  0.000000  0.000000
1  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000
3  0.000000  0.000000  0.000000
4  0.646053  0.856210  0.142555
5  0.368435  0.577341  0.799733
6  0.441040  0.998293  0.204467
7  0.759758  0.749011  0.731621

In [43]:
df3new

A     B      C         I        II       III
0  4.0  10.0  100.0  0.000000  0.000000  0.000000
1  5.0  20.0   50.0  0.000000  0.000000  0.000000
2  6.0  30.0  -30.0  0.000000  0.000000  0.000000
3  7.0  40.0  -50.0  0.000000  0.000000  0.000000
4  0.0   0.0    0.0  0.646053  0.856210  0.142555
5  0.0   0.0    0.0  0.368435  0.577341  0.799733
6  0.0   0.0    0.0  0.441040  0.998293  0.204467
7  0.0   0.0    0.0  0.759758  0.749011  0.731621

In [0]:
v=df3new["III"].idxmax(axis=0)

In [53]:
df3new["III"].iloc[v]

0.7997329841227782

In [0]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'A':[4,5,6,7],'B':[10,20,30,40], 'C':[100,50,-30,-50]})


In [55]:
df1

A   B    C
0  4  10  100
1  5  20   50
2  6  30  -30
3  7  40  -50

In [0]:
new_data = np.random.rand(4,3)

In [57]:
new_data

array([[0.27177208, 0.61554536, 0.61020063],
       [0.04426231, 0.76215822, 0.62355853],
       [0.47690494, 0.01146043, 0.1317637 ],
       [0.58923271, 0.02032264, 0.96826502]])

In [0]:
df2=pd.DataFrame(new_data,columns=["D","E","F"])

In [60]:
df2

D         E         F
0  0.271772  0.615545  0.610201
1  0.044262  0.762158  0.623559
2  0.476905  0.011460  0.131764
3  0.589233  0.020323  0.968265

In [63]:
pd.concat((df1,df2),axis=1,ignore_index=True)

0   1    2         3         4         5
0  4  10  100  0.271772  0.615545  0.610201
1  5  20   50  0.044262  0.762158  0.623559
2  6  30  -30  0.476905  0.011460  0.131764
3  7  40  -50  0.589233  0.020323  0.968265